name: GitHub Actions Demo
on: [push]
run-name: ${{ github.actor }} Has pushed code! 🚀
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'maven'
    - name: List files in the repository
      run: |
          ls ${{ github.workspace }}
    - name: Build java
      run: mvn clean install
    - name: List files gain
      run: find .
    - name: Set permissions
      run: chmod 700 ./target/demo1-0.0.1-SNAPSHOT.jar
    - name: Run
      run: timeout 10 ./target/demo1-0.0.1-SNAPSHOT.jar