name: GM build spring boot template
on:
  workflow_call:
    inputs:
      jar-name:
        required: true
        type: string
      container-name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Some tests here
      run: |
          ls ${{ github.workspace }}
    - name: Build java
      run: mvn clean install
    - name: Set permissions & move
      run: chmod 700 ./target/*.jar && mv ./target/*.jar ./${{inputs.jar-name}}
    - name: Test valid spring boot boot (pun intended)
      run: timeout 10 java -jar ./${{inputs.jar-name}} || true
    - name: Build Dockerfile
      run: docker build . -t ${{inputs.container-name}}:latest --build-arg jar-name=${{inputs.jar-name}}
    - name: Test valid container run
      run: timeout 10 docker run ${{inputs.container-name}}:latest || true
    - name: Push container to registry
      run: echo Pushing container to registry
