name: Build Spring Boot
on: [push]
run-name: ${{ github.actor }} Has pushed code! Non-abstracted run🚀
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Some tests here
      run: |
          ls ${{ github.workspace }}
    - name: Build java
      run: mvn clean install
    - name: Set permissions & move
      run: chmod 700 ./target/*.jar && mv ./target/*.jar ./demo1.jar
    - name: Test valid spring boot boot (pun intended)
      run: timeout 10 java -jar ./demo1.jar || true
    - name: Build Dockerfile
      run: docker build . -t demo1:latest --build-arg jar-name=demo1.jar
    - name: Test valid container run
      run: timeout 10 docker run demo1:latest || true
    - name: Push container to registry
      run: echo Pushing container to registry